package com.bootcamp.web.service;

import com.bootcamp.web.entity.Employee;
import com.bootcamp.web.entity.EmployeeAccount;
import com.bootcamp.web.entity.Reservation;

public interface EmailService {
	
	void sendAutoGeneratedPassword(Employee email, EmployeeAccount password);
	
	void sendReserveStatusUpdate(Reservation reservation, Employee email);
	
	void sendPasswordChange(Employee email);

}
